### ISSUE TITLE
Doesn't Create Volumes

### ISSUE THREAD

**Issue by tnargnai** [shortdudey123/chef-gluster#49]
Hi,

I am creating a Gluster cluster of two servers. I bootstrap the peer first and then the master.  Both servers build ok and the peer probe works displaying the servers in the cluster but the volumes aren't created. 

I have a default of 

`default['gluster']['server']['brick_mount_path'] = "/"`

and the following set in the environment file 

```
`"gluster": {
      "server": {
        "volumes": {
          "amq": {
            "peers": ["stg-inf-gfs-01.matchesremote.com", "stg-inf-gfs-02.matchesremote.com"],
            "replica_count": "2",
            "volume_type": "replicated",
            "lvm_volumes": ["share"]
          },
          "api": {
            "peers": ["stg-inf-gfs-01.matchesremote.com", "stg-inf-gfs-02.matchesremote.com"],
            "replica_count": "2",
            "volume_type": "replicated",
            "lvm_volumes": ["share"]
          },
          "hybris_dataimport": {
            "peers": ["stg-inf-gfs-01.matchesremote.com", "stg-inf-gfs-02.matchesremote.com"],
            "replica_count": "2",
            "volume_type": "replicated",
            "lvm_volumes": ["share"]
          },
          "hybris_media": {
            "peers": ["stg-inf-gfs-01.matchesremote.com", "stg-inf-gfs-02.matchesremote.com"],
            "replica_count": "2",
            "volume_type": "replicated",
            "lvm_volumes": ["share"]
          },
          "map": {
            "peers": ["stg-inf-gfs-01.matchesremote.com", "stg-inf-gfs-02.matchesremote.com"],
            "replica_count": "2",
            "volume_type": "replicated",
            "lvm_volumes": ["share"]
          },
          "mids": {
            "peers": ["stg-inf-gfs-01.matchesremote.com", "stg-inf-gfs-02.matchesremote.com"],
            "replica_count": "2",
            "volume_type": "replicated",
            "lvm_volumes": ["share"]
          },
          "nav": {
            "peers": ["stg-inf-gfs-01.matchesremote.com", "stg-inf-gfs-02.matchesremote.com"],
            "replica_count": "2",
            "volume_type": "replicated",
            "lvm_volumes": ["share"]
          }
        }
      }
    }`
```

Any ideas where I'm going wrong? 

Thanks

**Comment by shortdudey123** [comment]
Is there any error output?

I am guessing its because `default['gluster']['server']['brick_mount_path']` already exists (`/` is always used already so you can't mount something over the root partition)

**Comment by tnargnai** [comment]
Hi,

There is no error. Everything runs ok and I don't see anything in the output where it is trying to create the volumes.  On the server the peer probe is successful and the folders are created on the mount path it's just the final step of creating the volumes is not done. 

To make things a little easier I went back to running this in test kitchen with your own kitchen.yml file settings.

Recipe: 

```
#
# Cookbook Name:: mf-gluster
# Recipe:: server
#
# Copyright (c) 2015 The Authors, All Rights Reserved.

# Add the EPEL repo
yum_repository 'epel' do
  description 'Extra Packages for Enterprise Linux'
  mirrorlist 'http://mirrors.fedoraproject.org/mirrorlist?repo=epel-6&arch=$basearch'
  gpgkey 'http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6'
  action :create
end

# Build server
include_recipe 'gluster::server'
```

Kitchen file:

```
- name: replicated1
    driver:
      ipaddress: 192.168.10.10
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster1
      additional_disk:
        size: 1
    run_list:
      - recipe[mf-gluster::set_hostname]
      - recipe[mf-gluster::server]
    attributes:
      gluster:
        server:
          brick_mount_path: "/data"
          disks:
            - sdb
          volumes:
            gv0:
              peers:
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "replicated"

  - name: replicated2
    driver:
      ipaddress: 192.168.10.20
      vagrantfile_erb: test/integration/Vagrantfile.erb
      vm_hostname: gluster2
      additional_disk:
        size: 1
    run_list:
      - recipe[mf-gluster::set_hostname]
      - recipe[mf-gluster::server]
    attributes:
      gluster:
        server:
          disks:
            - sdb
          brick_mount_path: "/data"
          volumes:
            gv0:
              peers:
                - "gluster2"
                - "gluster1"
              replica_count: 2
              volume_type: "replicated"
```

This is the output (I've only included the last bit of the master converge: 

```
       Recipe: gluster::server_install
       
           - install version 3.1.1-16.el6 of package xfsprogs
       
           - install version 3.7.6-1.el6 of package glusterfs-server
        (up to date)
       
           - start service service[glusterd]
        (skipped due to only_if)
         * service[glusterfsd] action start (skipped due to only_if)
       Recipe: gluster::server_setup
       
           - execute "bash"  "/tmp/chef-script20151127-2451-81cqip"
         * execute[format partition] action run
           - execute mkfs.xfs -i size=512 /dev/sdb1
         * directory[/data/sdb1] action create
       
       
       
           - mount /dev/sdb1 to /data/sdb1
       
           - enable /dev/sdb1
       
       
           - restore selinux security context
       
           - execute gluster peer probe gluster1
        (skipped due to not_if)
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 22/23 resources updated in 38.111062814 seconds
       Finished converging <replicated2-centos-66> (2m54.64s).
-----> Kitchen is finished. (7m14.89s)
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
iang@matches:~/repos/matches/chef$ kitchen login replicated1
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
Last login: Fri Nov 27 12:46:45 2015 from 10.0.2.2
[vagrant@gluster1 ~]$ ll /data/
total 0
drwxr-xr-x. 3 root root 16 Nov 27 12:47 sdb1
[vagrant@gluster1 ~]$ ll /data/sdb1/gv0/
total 0
[vagrant@gluster1 ~]$ sudo -i
[root@gluster1 ~]# gluster peer status
Number of Peers: 1

Hostname: gluster2
Uuid: 24782800-50b4-453d-be6b-859b28d4b4ec
State: Peer in Cluster (Connected)
[root@gluster1 ~]# gluster volume status
No volumes present

```

Thanks for your help
